"""PROJECT_05 — Marchés Oubliés PAINs Registry."""
PAIN_IDS = ["PAIN_01_ACCESS_TO_SERVICES", "PAIN_02_STRUCTURED_OFFER_ABSENCE",
            "PAIN_03_UNDERVALUED_URBAN_POTENTIAL"]
__all__ = ["PAIN_IDS"]
