"""PROJECT_02 — Google XR PAINs Registry."""
PAIN_IDS = ["PAIN_URGENT_01_ENTERPRISE_XR", "PAIN_URGENT_02_TRAINING_XR",
            "PAIN_03_INDUSTRIAL_SIMULATION", "PAIN_04_DATA_VISUALIZATION",
            "PAIN_05_CUSTOM_XR_PLATFORM"]
__all__ = ["PAIN_IDS"]
