"""NAYA — Business Projects Package."""
PROJECT_IDS = [
    "PROJECT_01_CASH_RAPIDE",
    "PROJECT_02_GOOGLE_XR",
    "PROJECT_03_NAYA_BOTANICA",
    "PROJECT_04_TINY_HOUSE",
    "PROJECT_05_MARCHES_OUBLIES",
    "PROJECT_06_ACQUISITION_IMMOBILIERE",
]
__all__ = ["PROJECT_IDS"]
